version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cloth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - scrapy_network

  scrapy:
    build:
      context: ./Scraper/
    container_name: scrapy_container
    environment:
      - HOST=postgres_db
      - USER=user
      - DATABASE=cloth
      - PORT=5432
      - PASSWORD=password
    depends_on:
      - postgres
    networks:
      - scrapy_network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - postgres
    networks:
      - scrapy_network
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/cloth
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80" # Expose port 80 for NGINX
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mount your custom NGINX config
    depends_on:
      - backend
    networks:
      - scrapy_network

networks:
  scrapy_network:
    driver: bridge

volumes:
  postgres_data:
